apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        app.holos.run/cluster.name: workload
        app.holos.run/component.name: balance-reader
        app.holos.run/environment.name: dev
        app.holos.run/project.name: dev-bank-backend
        app.holos.run/stack.name: bank-of-holos
        app.holos.run/team.name: backend
    name: dev-bank-backend-balance-reader
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: dev-bank-backend
    source:
        path: deploy/clusters/workload/projects/dev-bank-backend/components/balance-reader
        repoURL: https://github.com/holos-run/bank-of-holos.git
        targetRevision: main
