apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        app.holos.run/cluster.name: workload
        app.holos.run/component.name: dev-bank-frontend
        app.holos.run/environment.name: dev
        app.holos.run/project.name: dev-bank-frontend
        app.holos.run/stack.name: bank-of-holos
        app.holos.run/team.name: frontend
    name: dev-bank-frontend-dev-bank-frontend
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: dev-bank-frontend
    source:
        path: deploy/clusters/workload/projects/dev-bank-frontend/components/dev-bank-frontend
        repoURL: https://github.com/jeffmccune/bank-of-holos.git
        targetRevision: main
