apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-crds
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: ./deploy/clusters/workload/components/external-secrets-crds
    repoURL: https://github.com/holos-run/bank-of-holos
    targetRevision: main
