apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.holos.run/cluster.name: management
    app.holos.run/component.name: namespaces
    app.holos.run/environment.name: test
    app.holos.run/project.name: test-bank-security
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: security
    argocd.argoproj.io/instance: test-bank-security-namespaces
    kubernetes.io/metadata.name: test-bank-backend
  name: test-bank-backend
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.holos.run/cluster.name: management
    app.holos.run/component.name: namespaces
    app.holos.run/environment.name: test
    app.holos.run/project.name: test-bank-security
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: security
    argocd.argoproj.io/instance: test-bank-security-namespaces
    kubernetes.io/metadata.name: test-bank-frontend
  name: test-bank-frontend
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.holos.run/cluster.name: management
    app.holos.run/component.name: namespaces
    app.holos.run/environment.name: test
    app.holos.run/project.name: test-bank-security
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: security
    argocd.argoproj.io/instance: test-bank-security-namespaces
    kubernetes.io/metadata.name: test-bank-security
  name: test-bank-security
