---
# Source: CUE apiObjects.AppProject.bank-backend
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bank-backend
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Holos managed AppProject
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
---
# Source: CUE apiObjects.AppProject.bank-frontend
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bank-frontend
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Holos managed AppProject
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
---
# Source: CUE apiObjects.AppProject.bank-security
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bank-security
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Holos managed AppProject
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
---
# Source: CUE apiObjects.AppProject.platform
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Holos managed AppProject
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
