apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        app.holos.run/cluster.name: workload
        app.holos.run/component.name: kargo
        app.holos.run/project.name: argocd
        app.holos.run/team.name: platform
    name: argocd-kargo
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: argocd
    source:
        path: deploy/clusters/workload/projects/argocd/components/kargo
        repoURL: https://github.com/jeffmccune/bank-of-holos.git
        targetRevision: main
