---
# Source: CUE apiObjects.Namespace.argocd
metadata:
  name: argocd
  labels:
    kubernetes.io/metadata.name: argocd
kind: Namespace
apiVersion: v1
---
# Source: CUE apiObjects.Namespace.bank-backend
metadata:
  name: bank-backend
  labels:
    kubernetes.io/metadata.name: bank-backend
kind: Namespace
apiVersion: v1
---
# Source: CUE apiObjects.Namespace.bank-frontend
metadata:
  name: bank-frontend
  labels:
    kubernetes.io/metadata.name: bank-frontend
kind: Namespace
apiVersion: v1
---
# Source: CUE apiObjects.Namespace.bank-security
metadata:
  name: bank-security
  labels:
    kubernetes.io/metadata.name: bank-security
kind: Namespace
apiVersion: v1
---
# Source: CUE apiObjects.Namespace.cert-manager
metadata:
  name: cert-manager
  labels:
    kubernetes.io/metadata.name: cert-manager
kind: Namespace
apiVersion: v1
---
# Source: CUE apiObjects.Namespace.external-secrets
metadata:
  name: external-secrets
  labels:
    kubernetes.io/metadata.name: external-secrets
kind: Namespace
apiVersion: v1
---
# Source: CUE apiObjects.Namespace.istio-ingress
metadata:
  name: istio-ingress
  labels:
    kubernetes.io/metadata.name: istio-ingress
kind: Namespace
apiVersion: v1
---
# Source: CUE apiObjects.Namespace.istio-system
metadata:
  name: istio-system
  labels:
    kubernetes.io/metadata.name: istio-system
kind: Namespace
apiVersion: v1
