apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        app.holos.run/cluster.name: workload
        app.holos.run/component.name: test-bank-secrets
        app.holos.run/environment.name: test
        app.holos.run/project.name: test-bank-security
        app.holos.run/stack.name: bank-of-holos
        app.holos.run/team.name: security
    name: test-bank-security-test-bank-secrets
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: test-bank-security
    source:
        path: deploy/clusters/workload/projects/test-bank-security/components/test-bank-secrets
        repoURL: https://github.com/jeffmccune/bank-of-holos.git
        targetRevision: main
