apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        app.holos.run/cluster.name: management
        app.holos.run/component.name: contacts
        app.holos.run/environment.name: stage
        app.holos.run/project.name: stage-bank-backend
        app.holos.run/stack.name: bank-of-holos
        app.holos.run/team.name: backend
    name: stage-bank-backend-contacts
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: stage-bank-backend
    source:
        path: deploy/clusters/management/projects/stage-bank-backend/components/contacts
        repoURL: https://github.com/holos-run/bank-of-holos.git
        targetRevision: main
