apiVersion: v1
data:
  POSTGRES_DB: postgresdb
  POSTGRES_PASSWORD: password
  POSTGRES_USER: admin
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-db:5432/postgresdb
  SPRING_DATASOURCE_USERNAME: admin
kind: ConfigMap
metadata:
  labels:
    app: ledger-db
    app.holos.run/cluster.name: management
    app.holos.run/component.name: ledger-db
    app.holos.run/environment.name: test
    app.holos.run/project.name: test-bank-backend
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: backend
    application: bank-of-holos
    argocd.argoproj.io/instance: test-bank-backend-ledger-db
    environment: development
    team: ledger
    tier: db
  name: ledger-db-config
  namespace: test-bank-backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.holos.run/cluster.name: management
    app.holos.run/component.name: ledger-db
    app.holos.run/environment.name: test
    app.holos.run/project.name: test-bank-backend
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: backend
    application: bank-of-holos
    argocd.argoproj.io/instance: test-bank-backend-ledger-db
    environment: development
    team: ledger
    tier: db
  name: ledger-db
  namespace: test-bank-backend
spec:
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
  selector:
    app: ledger-db
    application: bank-of-holos
    environment: development
    team: ledger
    tier: db
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.holos.run/cluster.name: management
    app.holos.run/component.name: ledger-db
    app.holos.run/environment.name: test
    app.holos.run/project.name: test-bank-backend
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: backend
    application: bank-of-holos
    argocd.argoproj.io/instance: test-bank-backend-ledger-db
    environment: development
    team: ledger
    tier: db
  name: ledger-db
  namespace: test-bank-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-db
      application: bank-of-holos
      environment: development
      team: ledger
      tier: db
  serviceName: ledger-db
  template:
    metadata:
      labels:
        app: ledger-db
        application: bank-of-holos
        environment: development
        team: ledger
        tier: db
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: environment-config
        - configMapRef:
            name: ledger-db-config
        - configMapRef:
            name: demo-data-config
        image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/ledger-db:v0.6.5@sha256:cc4fd25f301ab6d46b1312244d6931babc4c6cb66c5cb6d31d4a1adfa318a321
        name: postgres
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
          subPath: postgres
      serviceAccountName: bank-of-holos
      volumes:
      - emptyDir: {}
        name: postgresdb
