apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.holos.run/cluster.name: management
    app.holos.run/component.name: namespaces
    app.holos.run/environment.name: prod
    app.holos.run/project.name: prod-bank-security
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: security
    argocd.argoproj.io/instance: prod-bank-security-namespaces
    kubernetes.io/metadata.name: prod-bank-backend
  name: prod-bank-backend
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.holos.run/cluster.name: management
    app.holos.run/component.name: namespaces
    app.holos.run/environment.name: prod
    app.holos.run/project.name: prod-bank-security
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: security
    argocd.argoproj.io/instance: prod-bank-security-namespaces
    kubernetes.io/metadata.name: prod-bank-frontend
  name: prod-bank-frontend
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.holos.run/cluster.name: management
    app.holos.run/component.name: namespaces
    app.holos.run/environment.name: prod
    app.holos.run/project.name: prod-bank-security
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: security
    argocd.argoproj.io/instance: prod-bank-security-namespaces
    kubernetes.io/metadata.name: prod-bank-security
  name: prod-bank-security
