apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: bank-of-holos
    environment: dev
    example.com/environment.name: dev
    example.com/owner.name: backend
    example.com/tier.name: backend
    holos.run/component.name: dev-bank-ledger-writer
    team: backend
    tier: backend
  name: dev-bank-ledger-writer
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: dev-bank-backend
  source:
    path: examples/environments/deploy/clusters/workload/components/dev-bank-ledger-writer
    repoURL: https://github.com/holos-run/bank-of-holos
    targetRevision: main
