apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: bank-of-holos
    environment: prod
    example.com/environment.name: prod
    example.com/owner.name: security
    example.com/tier.name: foundation
    holos.run/component.name: prod-bank-projects
    team: security
    tier: foundation
  name: prod-bank-projects
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: prod-bank-security
  source:
    path: examples/environments/deploy/clusters/workload/components/prod-bank-projects
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: main
