apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: bank-of-holos
    environment: sandbox
    example.com/environment.name: sandbox
    example.com/owner.name: jeff
    example.com/tier.name: foundation
    holos.run/component.name: sandbox-jeff-bank-routes
    team: jeff
    tier: foundation
  name: sandbox-jeff-bank-routes
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: sandbox-jeff-bank-security
  source:
    path: deploy/clusters/workload/components/sandbox-jeff-bank-routes
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: main
