apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: bank-of-holos
    environment: sandbox
    example.com/environment.name: sandbox
    example.com/owner.name: jeff
    example.com/tier.name: backend
    holos.run/component.name: sandbox-jeff-bank-ledger-writer
    team: jeff
    tier: backend
  name: sandbox-jeff-bank-ledger-writer
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: sandbox-jeff-bank-backend
  source:
    path: examples/environments/deploy/clusters/workload/components/sandbox-jeff-bank-ledger-writer
    repoURL: https://github.com/holos-run/bank-of-holos
    targetRevision: main
